name: Generate and publish JavaDoc

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Generate JavaDoc
        run: ./gradlew javadoc
    
      - name: Move JavaDoc to /javadoc
        run: |
          mkdir -p javadoc
          cp -r lib/build/docs/javadoc/* javadoc/

      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 23
          target-folder: javadoc
          project: gradle
          javadoc-source-folder: lib/build/docs/javadoc