name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Publish to GitHub Packages
      run: ./gradlew :lib:publish
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.PAT_GITHUB }}
