name: Publish GitHub Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: git fetch --tags --unshallow

      - name: Generate Changelog
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "Dernier tag détecté : $LAST_TAG"
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          git log $LAST_TAG..HEAD --pretty=format:"%s" \
          | awk '
            /^feat/ { f = f "\n- 🚀 " $0 }
            /^fix/ { x = x "\n- 🐛 " $0 }
            /^core/ { c = c "\n- ⚙️ " $0 }
            !/^(feat|fix|core)/ { u = u "\n- 🔸 " $0 }
            END {
              print "## 🚀 Features" f "\n\n## 🐛 Fixes" x "\n\n## ⚙️ Core" c "\n\n## 🔸 Non classé" u
            }
          ' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
